core/urls.py
from django.contrib import admin
from django.urls import include, path

from core import settings

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_soft.urls'))
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserActivation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_activated = models.BooleanField(default=False)
    created_through_api = models.BooleanField(default=False)

class EncuestaEconomica(models.Model):
    nombre = models.CharField(max_length=200)


class GrupoPoblacional(models.Model):
    encuesta = models.ForeignKey(EncuestaEconomica, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)


class Apartado(models.Model):
    grupo = models.ForeignKey(GrupoPoblacional, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)


class PreguntaEconomica(models.Model):
    apartado = models.ForeignKey(Apartado, on_delete=models.CASCADE, null=True)
    encuesta = models.ForeignKey(EncuestaEconomica, on_delete=models.CASCADE)
    texto = models.TextField()


class RespuestaEconomica(models.Model):
    pregunta = models.ForeignKey(PreguntaEconomica, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    valor = models.IntegerField()
    predefinido = models.BooleanField(default=False)





class PreguntaAntropometria(models.Model):
    encuesta = models.ForeignKey(EncuestaEconomica, on_delete=models.CASCADE)
    texto = models.TextField()
    grupo_poblacional = models.CharField(max_length=60)  # campo para el grupo poblacional


class RespuestaNumerica(models.Model):
    encuesta = models.ForeignKey(EncuestaEconomica, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(PreguntaAntropometria, on_delete=models.CASCADE)
    respuesta_numerica = models.IntegerField()  # respuesta como número del 0 a 255
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    sesion_encuesta = models.CharField(max_length=64, blank=True, null=True)



class Encuesta(models.Model):
    id_encuesta = models.IntegerField(blank=False, null=False)
    encuestador = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    fecha = models.DateField()


    class Meta:
        db_table = 'encuesta'

class PreguntaRespuesta(models.Model):
    encuesta = models.ForeignKey(Encuesta, related_name='pregunta_respuesta', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    response = models.CharField(max_length=200)

class RespuestaUsuario(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    pregunta_respuesta = models.ForeignKey(PreguntaRespuesta, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    sesion_encuesta = models.CharField(max_length=64, blank=True, null=True)

templates/pages/SeleccionarPreguntas.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="container">

<h1>Selecciona las Preguntas</h1>
<form method="post">
    {% csrf_token %}
    {% for pregunta in preguntas %}
        <div>
            <label for="{{ pregunta }}">{{ pregunta }}</label>
            <input type="checkbox" id="{{ pregunta }}" name="{{ pregunta }}">
        </div>
    {% endfor %}
    <input type="submit" value="Enviar">
</form>
</body>
  
  
  </div>
{% endblock content %}

templates/pages/agregar_pregunta.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<form method="post" id="pregunta-form">
    {% csrf_token %}
    {{ form_pregunta.as_p }}
    <div id="respuestas-formset">
        {{ formset_respuesta.management_form }}
        {% for form_respuesta in formset_respuesta %}
            <div class="respuesta-form">
                {{ form_respuesta.id }}
                {{ form_respuesta.as_table }}
                <div class="opciones" style="display: none;">
                    {{ form_respuesta.opciones.label_tag }}
                    {{ form_respuesta.opciones }}
                </div>
            </div>
        {% endfor %}
    </div>
    <button type="submit">Guardar Pregunta</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#respuestas-formset').on('change', '[id$="-tipo"]', function() {
            var tipoRespuesta = $(this).val();
            var formContainer = $(this).closest('.respuesta-form');
            var opcionesField = formContainer.find('.opciones');

            opcionesField.toggle(tipoRespuesta === 'cerrada');
        });
    });
</script>

{% endblock content %}

templates/pages/encuestadores.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <h1>Encuestadores</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre de usuario</th>
            <th>Correo</th>
            <th>Encuestas Aplicadas</th>
        </tr>
        {% for encuestador in encuestadores %}
            <tr>
                <td>{{ encuestador.id }}</td>
                <td>{{ encuestador.username }}</td>
                <td>{{ encuestador.email }}</td>
                <td>{{ encuestador.num_encuestas }}</td>
            </tr>
        {% endfor %}
    </table>



{% endblock content %}

templates/pages/encuestas.html
{% extends 'layouts/base.html' %}
{% load bootstrap_icons %}
{% load static %}

{% block content %}

    <div class="container">

        {% for encuesta in encuestas %} <h1>{{ encuesta.nombre }}  <a href="{% url 'realizar_encuesta' encuesta.id %}">{% bs_icon 'plus' size='3vw'  %}</a>  </h1>
           
        {% endfor %}
    {% for usuario in usuarios %}
    <p>El usuario {{ usuario.username }} ha completado {{ usuario.num_encuestas }} encuestas.</p>
{% endfor %}




    </div>
{% endblock content %}

templates/pages/exito.html
exdito

templates/pages/inactive_users.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<body>
    <h1>Usuarios inactivos</h1>
    <ul>
        {% for user in users %}
            <li>
                <span>Usuario: {{ user.username }}</span>
                <a href="{% url "activate_user" user.username %}">Activar este usuario</a>
            </li>
        {% endfor %}
    </ul>
</body>



{% endblock content %}

templates/pages/realizar_encuesta.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <h1>{{ encuesta.nombre }}</h1>
    <hr>

    <form method="POST" class="form-check">
      {% csrf_token %}
      {% for pregunta in preguntas %}
        <p class="lead"> {{ pregunta.texto }}</p>
        {% if pregunta.respuestaeconomica_set.all %}
          {% for respuesta in pregunta.respuestaeconomica_set.all %}
            <input class="form-check-input" type="radio" name="{{ pregunta.id }}" value="{{ respuesta.id }}"> {{ respuesta.texto }}<br>
          {% endfor %}
        {% else %}
          <select class="form-control" name="{{ pregunta.id }}">
            {% for num in rangos %}
              <option value="{{ num }}">{{ num }}</option>
            {% endfor %}
          </select>
        {% endif %}
      {% endfor %}
      <input type="submit" class="btn btn-primary" value="Enviar respuestas">
    </form>
  </div>
{% endblock content %}

templates/pages/resultadoANOVA.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {% for item in id_encuestas %}
                <details>
                    <summary>ID de Encuesta: {{ item.id_encuesta }}</summary>
                    {% for nombre in item.nombres_encuesta %}
                        <!-- Aquí usamos el id de la encuesta en lugar del nombre -->
                        <input type="checkbox" name="encuestas_seleccionadas" value="{{ item.id_encuesta }}">
                        <label for="{{ nombre }}">Nombre de Encuesta: {{ nombre }}</label><br>
                    {% endfor %}
                </details>
            {% endfor %}
            <input type="submit" value="Seleccionar encuestas">
        </form>
    </div>
{% endblock content %}

templates/pages/resultadoANOVAanalisis.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    {% for username, user_data in users_data.items %}
        <details>
            <summary>{{ username }}</summary>
            <form method="POST">
                <table>
                    <tr>
                        <th>Select</th>
                        <th>Pregunta</th>
                        <th>Respuesta</th>
                        <th>Valor</th>
                    </tr>
                    {% for row in user_data %}
                        <tr>
                            <td><input type="checkbox" name="selected_rows"></td>
                            <td>{{ row.pregunta__texto }}</td>
                            <td>{{ row.respuesta__texto }}</td>
                            <td>{{ row.respuesta__valor }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <input type="submit" value="Realizar ANOVA">
            </form>
        </details>
    {% endfor %}
  </div>
{% endblock %}

templates/pages/tables.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid py-4">
<form method="POST">
  {% csrf_token %}
  <label for="analisis_estadistico">Elegir un análisis estadístico:</label>
  <select id="analisis_estadistico" name="analisis_estadistico">
    {% for analisis in analisis_estadisticos %}
    <option value="{{ analisis }}">{{ analisis }}</option>
    {% endfor %}
  </select>
  <input type="submit" value="Realizar análisis">
</form>
  
    
</div>
  {% endblock content %}

templates/pages/virtual-reality.html
<!--
=========================================================
* Soft UI Dashboard - v1.0.6
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">

  <title>
    Soft UI Dashboard - VR Page | AppSeed
  </title>
  
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/soft-ui-dashboard.css' %}" rel="stylesheet" />
  <link id="pagestyle_dark" href="{% static 'css/dark-theme-core.css' %}" rel="stylesheet" />

</head>
<body class="g-sidenav-show  bg-gray-100 virtual-reality">

  <div> 
    {% include "includes/navigation.html" %}
  </div>  
  
  <div class="border-radius-xl mt-3 mx-3 position-relative" style="background-image: url('{% static 'img/vr-bg.jpg' %}') ; background-size: cover;">

    {% include "includes/sidebar.html" %}

    <main class="main-content mt-1 border-radius-lg">

      <div class="section min-vh-85 position-relative transform-scale-0 transform-scale-md-7">
        <div class="container">
          <div class="row pt-10">
            <div class="col-lg-1 col-md-1 pt-5 pt-lg-0 ms-lg-5 text-center">
              <a href="javascript:;" class="avatar avatar-md border-0" data-bs-toggle="tooltip" data-bs-placement="left" title="My Profile">
                <img class="border-radius-lg" alt="Image placeholder" src="{% static 'img/team-1.jpg' %}">
              </a>
              <button class="btn btn-white border-radius-lg p-2 mt-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Home">
                <i class="fas fa-home p-2"></i>
              </button>
              <button class="btn btn-white border-radius-lg p-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Search">
                <i class="fas fa-search p-2"></i>
              </button>
              <button class="btn btn-white border-radius-lg p-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Minimize">
                <i class="fas fa-ellipsis-h p-2"></i>
              </button>
            </div>
            <div class="col-lg-8 col-md-11">
              <div class="d-flex">
                <div class="me-auto">
                  <h1 class="display-1 font-weight-bold mt-n4 mb-0">28°C</h1>
                  <h6 class="text-uppercase mb-0 ms-1">Cloudy</h6>
                </div>
                <div class="ms-auto">
                  <img class="w-50 float-end mt-lg-n4" src="{% static 'img/small-logos/icon-sun-cloud.png' %}" alt="image sun">
                </div>
              </div>
              <div class="row mt-4">
                <div class="col-lg-4 col-md-4">
                  <div class="card move-on-hover overflow-hidden">
                    <div class="card-body">
                      <div class="d-flex">
                        <h6 class="mb-0 me-3">08:00</h6>
                        <h6 class="mb-0">Synk up with Mark
                          <small class="text-secondary font-weight-normal">Hangouts</small>
                        </h6>
                      </div>
                      <hr class="horizontal dark">
                      <div class="d-flex">
                        <h6 class="mb-0 me-3">09:30</h6>
                        <h6 class="mb-0">Gym <br />
                          <small class="text-secondary font-weight-normal">World Class</small>
                        </h6>
                      </div>
                      <hr class="horizontal dark">
                      <div class="d-flex">
                        <h6 class="mb-0 me-3">11:00</h6>
                        <h6 class="mb-0">Design Review<br />
                          <small class="text-secondary font-weight-normal">Zoom</small>
                        </h6>
                      </div>
                    </div>
                    <a href="javascript:;" class="bg-gray-100 w-100 text-center py-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Show More">
                      <i class="fas fa-chevron-down text-primary"></i>
                    </a>
                  </div>
                </div>
                <div class="col-lg-4 col-md-4 mt-4 mt-sm-0">
                  <div class="card bg-gradient-dark move-on-hover">
                    <div class="card-body">
                      <div class="d-flex">
                        <h5 class="mb-0 text-white">To Do</h5>
                        <div class="ms-auto">
                          <h1 class="text-white text-end mb-0 mt-n2">7</h1>
                          <p class="text-sm mb-0 text-white">items</p>
                        </div>
                      </div>
                      <p class="text-white mb-0">Shopping</p>
                      <p class="mb-0 text-white">Meeting</p>
                    </div>
                    <a href="javascript:;" class="w-100 text-center py-1" data-bs-toggle="tooltip" data-bs-placement="top" title="Show More">
                      <i class="fas fa-chevron-down text-white"></i>
                    </a>
                  </div>
                  <div class="card move-on-hover mt-4">
                    <div class="card-body">
                      <div class="d-flex">
                        <p class="mb-0">Emails (21)</p>
                        <a href="javascript:;" class="ms-auto" data-bs-toggle="tooltip" data-bs-placement="top" title="Check your emails">
                          Check
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-md-4 mt-4 mt-sm-0">
                  <div class="card card-background card-background-mask-primary move-on-hover align-items-start">
                    <div class="cursor-pointer">
                      <div class="full-background" style="background-image: url('{% static 'img/curved-images/curved1.jpg' %}')"></div>
                      <div class="card-body">
                        <h5 class="text-white mb-0">Some Kind Of Blues</h5>
                        <p class="text-white text-sm">Deftones</p>
                        <div class="d-flex mt-5">
                          <button class="btn btn-outline-white rounded-circle p-2 mb-0" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Prev">
                            <i class="fas fa-backward p-2"></i>
                          </button>
                          <button class="btn btn-outline-white rounded-circle p-2 mx-2 mb-0" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Pause">
                            <i class="fas fa-play p-2"></i>
                          </button>
                          <button class="btn btn-outline-white rounded-circle p-2 mb-0" type="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Next">
                            <i class="fas fa-forward p-2"></i>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card move-on-hover mt-4">
                    <div class="card-body">
                      <div class="d-flex">
                        <p class="my-auto">Messages</p>
                        <div class="ms-auto">
                          <div class="avatar-group">
                            <a href="javascript:;" class="avatar avatar-sm border-0 rounded-circle" data-bs-toggle="tooltip" data-bs-placement="top" title="2 New Messages">
                              <img alt="Image placeholder" src="{% static 'img/team-1.jpg' %}">
                            </a>
                            <a href="javascript:;" class="avatar avatar-sm border-0 rounded-circle" data-bs-toggle="tooltip" data-bs-placement="top" title="1 New Message">
                              <img alt="Image placeholder" src="{% static 'img/team-2.jpg' %}">
                            </a>
                            <a href="javascript:;" class="avatar avatar-sm border-0 rounded-circle" data-bs-toggle="tooltip" data-bs-placement="top" title="13 New Messages">
                              <img alt="Image placeholder" src="{% static 'img/team-3.jpg' %}">
                            </a>
                            <a href="javascript:;" class="avatar avatar-sm border-0 rounded-circle" data-bs-toggle="tooltip" data-bs-placement="top" title="7 New Messages">
                              <img alt="Image placeholder" src="{% static 'img/team-4.jpg' %}">
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    
    </main>
    
  </div>

  {% include "includes/footer.html" %}

  <!-- APP Configurator -->
  {% include "includes/fixed-plugin.html" %} 

  <!-- Core JS Files -->
  {% include "includes/scripts.html" %}

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/soft-ui-dashboard.min.js' %}"></script>

</body>
</html>